CREATE SCHEMA IF NOT EXISTS ENRICH AUTHORIZATION SA;

CREATE TABLE IF NOT EXISTS ENRICH.INCIDENT(
    ID BINARY NOT NULL,
    INCIDENT_JSON CLOB NOT NULL,
    WEATHER CLOB NOT NULL,
    TIME_OF_INCIDENT TIMESTAMP NOT NULL
);
ALTER TABLE ENRICH.INCIDENT ADD CONSTRAINT IF NOT EXISTS
    ENRICH.INCIDENT_PK PRIMARY KEY(ID);